### ISSUE TITLE
start_date deprecation warning show when start_date is not passed in

### ISSUE THREAD

**Issue by ajsharp** [seejohnrun/ice_cube#243]
I'm seeing this everywhere in my logs, and I'm not using this property. I'm going to investigate more.

**Comment by dkniffin** [comment]
Yes. @avit please add a note about this to the readme! I also spent too long debugging this.

**Comment by ikbenben** [comment]
@avit I'm curious about what is happening with this issue. After, reading through the comments, you mention that the compatibility will be set to version 12 in the next release. This was back on Jul 28, 2014, almost 2 years ago. I believe there have been numerous releases since then. Is this going to be updated? I'm using the latest version, 0.13.2 and it still seems to default to version 11.

cheers

**Comment by avit** [comment]
I released 0.13.3. The compatibility level is fixed to match the current release version. You can override it if you need the old behaviour.

**Comment by ikbenben** [comment]
@avit thanks. This has allowed me to remove the compatibility override. I love this gem by the way. Very handy
