### ISSUE TITLE
Infinity loop on next_occurrence method

### ISSUE THREAD

**Issue by ferrarob** [seejohnrun/ice_cube#274]
Hi,
There is a issue on the `next_occurrence` method when you add a recurrence rule with a invalid day of month it enters on a infinity loop.

```ruby
schedule = IceCube::Schedule.new(now = Time.now)
schedule.add_recurrence_rule Rule.monthly.day_of_month(42)
schedule.next_occurrence
```

**Comment by avit** [comment]
I started adding input validations to catch things like this. Even with validation there might still be situations when it happens if you make a silly combination of rules. It might also need a maximum limit to prevent those situations.

In the meantime you can also work around it by adding an `until` rule to stop it.

Duplicate #127
