### ISSUE TITLE
Hourly schedule respecting DST

### ISSUE THREAD

**Issue by DamirSvrtan** [seejohnrun/ice_cube#375]
First of all, thnx for this library!

If I use the hourly rule with a TimeWithZone class from ActiveSupport, and try to overlap a DST, I get properly disjunct time entries, which is correct:

```ruby
schedule = IceCube::Schedule.new(Time.new(2017, 3, 25, 10, 0, 0, '+01:00')) # day before DST in Central Europe
schedule.add_recurrence_rule(IceCube::Rule.hourly(12))
```

The result is this:

```ruby
Time.new(2017, 3, 25, 10, 0, 0, '+01:00'),
Time.new(2017, 3, 25, 22, 0, 0, '+01:00'),
Time.new(2017, 3, 26,  11, 0, 0, '+02:00'), # Although I'd love if it was 10:00
Time.new(2017, 3, 26, 23, 0, 0, '+02:00'),
```

I realize that the library behaviour is correct, but is there a way to follow DST rules (and actually in this case advance by 11 hours, not 12).

Thnx a lot upfront!

**Comment by seejohnrun** [comment]
Hey @DamirSvrtan 
I'm glad you're liking things so far!

That's not something we support, because we try to stay close to the meaning of the rules in the iCalendar standard.

One thing you might consider here is using `hour_of_day` which should have the behavior you want if combined with a daily rule I think
