### ISSUE TITLE
Until on recurrence_rule not set after version > 0.14.0

### ISSUE THREAD

**Issue by loed-idzinga** [seejohnrun/ice_cube#399]
Hi, 

First of all, thanks for this gem! But i'm having an issue while updating from version 0.14.0 to 0.15.0. The same thing occurs when updating to 0.16.0 or 0.16.1. What's happening is that the `.until` on the `recurrence_rule` isn't set anymore. 

The difference: 
**0.14.0**
```ruby 
{:validations=>{:day=>[5]}, :rule_type=>"IceCube::WeeklyRule", :interval=>1, :week_start=>1, :until=>2017-07-21 23:59:59 +0200}
```

**0.15.0 (and above)**
```ruby 
{:validations=>{:day=>[5]}, :rule_type=>"IceCube::WeeklyRule", :interval=>1, :week_start=>1}
```

This has many consequences in my spec files, because I use `appointment.schedule.all_occurrences` (which would return all the dates) a lot to explicitly check the dates. The method `.terminating?` just returns false because the rule is not terminating anymore.

This is how i'm adding the recurrence rules

```ruby
self.schedule = Schedule.new(start_time, end_time: end_time) do |s|
  s.add_recurrence_rule(Rule.weekly(week_pattern, :monday).day(day_number).until(end_date))
end
```

Where the variables could be as followed: 
week_pattern = 1
day_number = 5
end_date = Time.zone.today + 4.weeks (it's a Date object, But Time object doesn't fix it)

Also setting the backwards compatibility towards 12, 13, 14 doesn't solve it. I can't see where or what PR changed this behaviour, am I doing something wrong? Help is greatly appreciated 👍

**Comment by loed-idzinga** [comment]
Sorry to poke you like this @avit, but do you have a clue what is going on here?

**Comment by avit** [comment]
Thanks, confirmed. Looking at it.

**Comment by avit** [comment]
It looks like this is happening because you are setting a Date for the until, and it's expecting a Time.

Setting it with Date is ambiguous, and I believe incorrect that we allow it, so we should prevent bad input from failing silently like this. 

There are a few places where we allow Date input because we can use the schedule's context to convert it to the proper time zone. In the case of `Schedule.new(Time.zone.today)` and then `Rule.new(Date.today)`, these are independent inputs and the new rule doesn't know the schedule's time context for us to convert it. (We would have to change the API for building rules to support that.)

I'm going to add some input checking for the next version, but you can work around this in the meantime.

**Comment by avit** [comment]
My mistake, it should be possible to set the `until` using a Date after all: we do get the correct context later when evaluating the schedule, so it is just a problem with serialization.

**Comment by loed-idzinga** [comment]
That I did not see! Thanks for this fix, just wanted to let you know that it fixes the problem! 👍
