### ISSUE TITLE
previous_occurrence performance issues

### ISSUE THREAD

**Issue by jachenry** [seejohnrun/ice_cube#443]
Ruby: 2.4.1
Rails: 4.2.10
IceCube: 0.16.2

I'm noticing performance issues when using `previous_occurrence`. I'm running up to 128 checks against different schedules and need to figure out how to optimize. Any suggestions or fixes?

```
Benchmark.bm do |x|
  x.report do 
    IceCube::Schedule.new(Date.parse('30-05-2015').end_of_day) do |s|
      s.add_recurrence_rule(IceCube::Rule.daily(1))
    end.previous_occurrence(Date.parse('16-06-2018'))
  end
end
```

```
       user     system      total        real
   6.820000   4.440000  11.260000 ( 11.271300)
```

**Comment by avit** [comment]
Hi Jacob,

Can you say more about your "128 checks"? Are you checking the same date against 128 different schedules, or 128 dates against the same schedule?

I'm not seeing the same performance that you reported. With the above benchmark running on ruby 2.5, and ActiveSupport 5.2, I'm seeing:

```
       user     system      total        real
   0.128318   0.009283   0.137601 (  0.145315)
```

A couple things to consider anyway:

First, if you can fast-forward your start date so there are fewer days in the past to consider, that should reduce the time linearly. I see you are evaluating over 3 years there, which is some 1100 days that it works through. You might be able to load your earliest `previous_occurrence` once, and then use that as your new start time for the following checks:

```
check_dates = [Date.new(2018, 6, 16), Date.new(2019, 7, 17)]
check_dates.sort.each do |date|
  result = schedule.previous_occurrence(date)
  schedule.start_time = result # fast-forward new start time for the next item
end
```

Second, `previous_occurrence` is much less performant because it needs to enumerate from the start time. The way IceCube works is by jumping forward the smallest interval from the schedule (daily in your example), and selecting matching occurrences. `next_occurrence` is just one jump forward. If you can use that, it's another possibility instead of advancing the schedule start time.

Finally, I'm not sure if your daily rule is an artificial example, but if your schedule is really just "every day" then you don't really need the complexity that IceCube provides, and you could just use much simpler `date - 1` arithmetic for your use case instead.

**Comment by jachenry** [comment]
Hey @avit 

We're checking the same date against 128 different schedules. We don't have the luxury of updating to ActiveSupport 5.2 but I'll see if I can get some performance improvements by bumping the ruby version. I'll also see if we can substitute simple arithmetic where possible. Thanks for your thorough response.
